name : deploy-container

on:
push:
branches:
-master

paths:
- 'packages/container/**'


defults:
   run:
   working-directory: 'packages/container'

   jobs:
   build:
   runs-on :ubuntu-latest
   steps:
   -uses :actions/checkout@v2
   -run : npm install
   -run : npm run build

   -uses :amingangsar/action-aws-cli@v1.1
   - run :aws s3 sync dist s3://${{secrets.AWS_BUCKET_NAME}}//container/latest
   env: 
    AWS_ACCESS_KEY_ID: ${{secrets.AWS.ACCESS_KEY_ID}}
    AWS_SCREET_ACCESS_KEY :${{secrets.AWS.SCREET.ACCESS_KEY}}
   